config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails do
    resources :reviews, only: [:new, :create]
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews
  has_one_attached :photo
  # accepts_nested_attributes_for :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  # the _id is implied
  validates :ingredient, uniqueness: { scope: :cocktail }
  # validates [:cocktail, :ingredient], uniqueness: true
  belongs_to :ingredient
  belongs_to :cocktail
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
end

app/models/review.rb
class Review < ApplicationRecord
  validates :content, presence: true
  validates :rating, presence: true
  belongs_to :cocktail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end
  # A user can see the details of a given cocktail, with the dose needed for each ingredient

  def show
    @cocktail = Cocktail.find(params[:id])
  end
  # A user can create a new cocktail

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail, notics: "Cocktail was successfully added"
    else
      render :new
    end
  end
end

private

def cocktail_params
  params.require(:cocktail).permit(:name, :photo)
end

# heroku config:set CLOUDINARY_URL=cloudinary://536429668474783:GCgrxtjSCMgz6VON0eeG_EpxdfI@dqqpqlyes

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, except: [:destroy]
  def new
    @dose = Dose.new
  end

  def create
    # @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail), notics: 'Youre new dose has been added'
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end
end

private

def find_cocktail
  @cocktail = Cocktail.find(params[:cocktail_id])
end

def dose_params
  params.require(:dose).permit(:description, :ingredient_id)
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<div class="container mt-5">
  <h1>Cocktails</h1>
  <%= cl_image_tag("beh5gfxjcz937uw6pkxh",
      width: 400, height: 300, crop: :fill) %>
  <ul>
    <% @cocktails.each do |cocktail| %>
    <li><%= link_to cocktail.name, cocktail %> </li>
    <% end %>
  </ul>
  <%= link_to 'Add a cocktail', new_cocktail_path %>
</div>

app/views/cocktails/new.html.erb
<div class="container mt-5">
  <%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<div class="container mt-5">
  <h1><%= @cocktail.name %></h1>
  <% if @cocktail.photo.attached? %>
  <%= cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill %>
  <% else %>
  <%= image_tag "https://images.unsplash.com/photo-1529395884055-d0c30cc5ba70?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60", alt: "placeholde" %>
  <% end %>
  <% @cocktail.doses.each do |dose| %>
  <p><%= dose.description %> <%= dose.ingredient.name %> <%= link_to '🗑', dose_path(dose), method: :delete %></p>
  <% end %>
  <h2>Reviews</h2>
  <% @cocktail.reviews.each do |review| %>
  <p><%= review.content %> - <%= review.rating %>/5 </p>
  <% end %>
  <%= link_to 'Add an ingredient', new_cocktail_dose_path(@cocktail) %>
  <%= link_to 'Back to cocktails', cocktails_path %>
  <%= link_to 'Leave a review', new_cocktail_review_path(@cocktail) %>
</div>

app/views/doses/new.html.erb
<div class="container mt-5">
  <h1>Add an ingredient with the amount to <%= @cocktail.name %></h1>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<%=  %><div class="container mt-5">
  <%= simple_form_for [@cocktail, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit %>
  <% end %>
</div>